package:
  name: perl-ska-agasc
  version: !!str 3.5.0

source:
 url: https://cxc.harvard.edu/mta/ASPECT/skare3-static-pkgs/Ska-AGASC-3.5.0.tar.gz

build:
 number: 1

requirements:
  host:
    - perl
    - perl-extended-deps
    - perl-chandra-time
    - perl-app-env-ascds
    - perl-ska-classic
  run:
    - perl
    - perl-extended-deps
    - perl-chandra-time
    - perl-app-env-ascds
    - perl-ska-classic
    - perl-ska-convert

test:
  # Perl 'use' tests
  imports:
    - Ska::AGASC

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

