package:
  name: perl-app-cpanminus
  version: 1.7047

source:
  url: http://www.cpan.org/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7047.tar.gz

build:
  number: 1

requirements:
  build:
     - conda-forge::perl==5.32.1
  run:
     - perl==5.32.1

