package:
  name: perl-app-cpanminus
  version: 1.7044

source:
  url: http://www.cpan.org/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7044.tar.gz

build:
  number: 1

requirements:
  host:
     - conda-forge::perl =5.26.2 # [linux]
     - perl # [osx]

  run:
     - perl

