package:
  name: perl-extended-deps
  version: 0.3.1

source:
  url:  https://cxc.harvard.edu/mta/ASPECT/skare3-static-pkgs/cpan-core-0.3.tar.gz

# On Linux, build seems to require conda-forge perl-5.26.2-h516909a_1006.tar.bz2,
# 5.26.2 linux package from defaults seems broken as of 26-Jun-2020.
requirements:
  build:
   - {{ compiler('c') }}
   - {{ compiler('cxx') }}
  host:
   - conda-forge::perl =5.26.2 # [linux]
   - perl =5.26.2 # [osx]
   - perl-app-cpanminus
   - perl-core-deps
   - expat
   - pkg-config
   - libpng
   - xtime
   - gsl
   - openssl
   - blas
   - mkl_fft
   - yaml
   - zlib
   - zip
   - cfitsio
  run:
   - perl
   - perl-app-cpanminus
   - perl-core-deps
   - pkg-config
   - libpng
   - xtime
   - gsl
   - openssl
   - blas
   - mkl_fft
   - yaml
   - expat
   - zlib
   - zip
   - cfitsio
build:
   number: 0







