package:
  name: perl-extended-deps
  version: 0.4.0

source:
  url:  https://cxc.harvard.edu/mta/ASPECT/skare3-static-pkgs/cpan-core-0.4.tar.gz

# On Linux, build seems to require conda-forge perl-5.26.2-h516909a_1006.tar.bz2,
# 5.26.2 linux package from defaults seems broken as of 26-Jun-2020.
requirements:
  build:
   - {{ compiler('c') }}
   - {{ compiler('cxx') }}
  host:
   - conda-forge::perl ==5.32.1
   - perl-app-cpanminus
   - perl-core-deps ==0.4.0
   - perl-io-tty >=1.20
   - expat
   - pkg-config
   - libpng
   - xtime
   - gsl
   - openssl
   - blas
   - mkl_fft
   - yaml
   - zlib ==1.2.13
   - libzlib ==1.2.13
   - zip
   - cfitsio
  run:
   - perl
   - perl-app-cpanminus
   - perl-io-tty >=1.20
   - perl-core-deps ==0.4.0
   - pkg-config
   - libpng
   - xtime
   - gsl
   - openssl
   - blas
   - mkl_fft
   - yaml
   - expat
   - zlib
   - zip
   - cfitsio
build:
   number: 2







