package:
  name: perl-tk
  version: "804.036"

source:
  url: https://cpan.metacpan.org/authors/id/S/SR/SREZIC/Tk-804.036.tar.gz

build:
  number: 0

requirements:
  build:
     - gcc ==13.2.0
     - {{ compiler('cxx') }}
  host:
     - conda-forge::perl ==5.32.1 # [linux]
     - perl # [osx]
     - xorg-libx11
     - xorg-libxft
     - xorg-xproto
     - libx11-devel-cos7-x86_64
     - libx11-cos7-x86_64
     - libx11-common-cos7-x86_64
     - libjpeg-turbo-cos7-x86_64
     - perl-extended-deps ==0.5.0
     - zlib
     - freetype
     - libpng
     - libzlib
  run:
     - perl ==5.32.1
     - xorg-libx11
     - xorg-libxft
     - xorg-xproto
     - libx11-devel-cos7-x86_64
     - libx11-cos7-x86_64
     - libx11-common-cos7-x86_64
     - libjpeg-turbo-cos7-x86_64
     - perl-extended-deps ==0.5.0
     - zlib
     - freetype
     - libpng
     - libzlib
