package:
  name: perl-dbd-sybase
  version: !!str 1.24

source:
  url: http://cpan.metacpan.org/authors/id/M/ME/MEWP/DBD-Sybase-1.24.tar.gz


build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1


requirements:
  host:
    - {{ compiler('c') }}
    - conda-forge::perl =5.32.1 # [linux]
    - perl # [osx]
    - perl-extended-deps
  run:
    - perl =5.32.1
    - perl-extended-deps


#test:
  # Perl 'use' tests
  #  - DBD::Sybase

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://metacpan.org/pod/DBD-Sybase
  license: unknown
  summary: 'Sybase database driver for the DBI module'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
