package:
  name: perl-astro-fits-cfitsio
  version: "1.15"

source:
   url: https://cpan.metacpan.org/authors/id/P/PR/PRATZLAFF/Astro-FITS-CFITSIO-1.15.tar.gz

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
   - {{ compiler('c') }}
   - {{ compiler('cxx') }}
  host:
   - conda-forge::perl ==5.32.1
   - conda-forge::perl-app-cpanminus
   - perl-extended-deps ==0.5.0
   - expat
   - pkg-config
   - yaml
   - zlib ==1.3.1
   - zip
  run:
   - perl
   - perl-app-cpanminus
   - perl-extended-deps ==0.5.0
   - expat
   - pkg-config
   - yaml
   - zlib ==1.3.1
   - zip

