package:
  name: perl-ska-convert
  version: !!str 4.3

source:
 url: https://cxc.harvard.edu/mta/ASPECT/skare3-static-pkgs/Ska-Convert-4.3.tar.gz

build:
 number: 3

requirements:
  host:
    - conda-forge::perl =5.32.1 # [linux]
    - perl # [osx]
    - perl-chandra-time
    - perl-ska-classic
  run:
    - perl
    - perl-chandra-time
    - perl-ska-classic

test:
  # Perl 'use' tests
  imports:
    - Ska::Convert

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

