package:
  name: perl-pdl
  version: 2.089

source:
  url: https://cpan.metacpan.org/authors/id/E/ET/ETJ/PDL-2.089.tar.gz
  patches:
    - no_gd.patch

build:
  number: 1

requirements:
  host:
     - {{ compiler('c') }}
     - {{ compiler('cxx') }}
     - conda-forge::perl==5.32.1 
     - perl-extended-deps ==0.5.0
     - perl-alien-cfitsio
     - perl-astro-fits-cfitsio
     - perl-astro-fits-header
     - perl-astro-fits-cfitsio-checkstatus
  run:
     - perl==5.32.1
     - perl-extended-deps ==0.5.0
     - perl-alien-cfitsio
     - perl-astro-fits-cfitsio
     - perl-astro-fits-header
     - perl-astro-fits-cfitsio-checkstatus
