package:
  name: perl-astro-fits-cfitsio-checkstatus
  version: "0.03"

source:
  url: https://cpan.metacpan.org/authors/id/D/DJ/DJERIUS/Astro-FITS-CFITSIO-CheckStatus-0.03.tar.gz
   #  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 0

requirements:
  build:
     - {{ compiler('c') }}
     - {{ compiler('cxx') }}
  host:
    - conda-forge::perl =5.32.1 # [linux]
    - perl # [osx]
    - perl-extended-deps ==0.5.0
    - perl-alien-cfitsio ==4.4.0.2
    - perl-astro-fits-header
    - perl-astro-fits-cfitsio
  run:
    - perl
    - perl-extended-deps ==0.5.0
    - perl-alien-cfitsio ==4.4.0.2
    - perl-astro-fits-header
    - perl-astro-fits-cfitsio
#test:
#  # Perl 'use' tests
#  imports:
#    - Ska::Convert

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

