package:
  name: xtime
  version: 1.2.2

source:
# The source section specifies where the source code of the package is coming
# from, it may be coming from a source tarball like:
  url: file:///proj/sot/ska/pkgs/XTime-1.2.2.tar.gz

requirements:
   host:
    - clangxx_osx-64 # [osx]
    - gxx_linux-64 # [linux]

build:
   number: 0




