package:
  name: xtime
  version: 1.2.2

source:
# The source section specifies where the source code of the package is coming
# from, it may be coming from a source tarball like:
  url: https://cxc.harvard.edu/mta/ASPECT/skare3-static-pkgs/XTime-1.2.2.tar.gz

requirements:
   build:
    - {{ compiler('cxx') }}

build:
   number: 1




