package:
  name: perl-app-env-ascds
  version: !!str 0.04

source:
  url: https://cxc.harvard.edu/mta/ASPECT/skare3-static-pkgs/App-Env-ASCDS-0.04_ska.tar.gz
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 1

requirements:
  host:
    - conda-forge::perl =5.26.2 # [linux]
    - perl # [osx]
    - perl-extended-deps
    - perl-cxc-sysarch
  run:
    - perl
    - perl-extended-deps
    - perl-cxc-sysarch

#test:
#  # Perl 'use' tests
#  imports:
#    - Ska::Convert

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

