package:
  name: perl-inline-python
  version: !!str 0.57

source:
  url: https://cxc.harvard.edu/mta/ASPECT/skare3-static-pkgs/Inline-Python-0.57.tar.gz

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  host:
   - {{ compiler('c') }}
   - {{ compiler('cxx') }}
   - conda-forge::perl =5.26.2 # [linux]
   - perl =5.26.2 # [osx]
   - perl-core-deps
   - perl-app-cpanminus
   - expat
   - pkg-config
   - python ==3.10.8
   - yaml
   - zlib
   - zip
  run:
   - perl =5.26.2
   - perl-app-cpanminus
   - perl-core-deps
   - expat
   - pkg-config
   - python
   - yaml
   - zlib
   - zip

