package:
  name: perl-core-deps
  version: 0.1

source:
  url:  file:///proj/sot/ska/pkgs/cpan-core-0.1.tar.gz

requirements:
  build:
   - perl
   - perl-app-cpanminus
   - pkg-config
   - libpng
   - cfitsio
   - pgplot [linux]
   - xtime
   - gsl
   - openssl
   - openblas
   - gcc ==4.8.5 [linux]
   - libgcc ==4.8.5 [linux]
   - libgfortran [linux]
  run:
   - perl
   - perl-app-cpanminus
   - pkg-config
   - libpng
   - cfitsio
   - pgplot [linux]
   - xtime
   - gsl
   - openssl
   - openblas
   - libgcc ==4.8.5 [linux]
   - libgfortran [linux]


build:
   number: 0







