package:
  name: perl-core-deps
  version: 0.5.0

source:
  url:  https://cxc.harvard.edu/mta/ASPECT/skare3-static-pkgs/cpan-core-0.5.tar.gz

# On Linux, build seems to require conda-forge perl-5.26.2-h516909a_1006.tar.bz2,
# 5.26.2 linux package from defaults seems broken as of 26-Jun-2020.
requirements:
  build:
   - {{ compiler('c') }}
   - {{ compiler('cxx') }}
  host:
   - conda-forge::perl ==5.32.1
   - perl-app-cpanminus
   - perl-io-tty ==1.16 # [osx and x86_64]
   - perl-io-tty >=1.20 # [linux or arm64]
   - expat
   - pkg-config
   - yaml
   - zip
  run:
   - perl >=5.32
   - perl-app-cpanminus
   - perl-io-tty ==1.16 # [osx and x86_64]
   - perl-io-tty >=1.20 # [linux or arm64]
   - expat
   - pkg-config
   - yaml
   - zip
build:
   number: 2







