package:
  name: perl-alien-cfitsio
  version: "4.4.0.2"

source:
  url: https://cpan.metacpan.org/authors/id/D/DJ/DJERIUS/Alien-CFITSIO-v4.4.0.2.tar.gz
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 0

requirements:
  host:
    - conda-forge::perl =5.32.1 # [linux]
    - perl # [osx]
    - perl-extended-deps ==0.5.0
  run:
    - perl
    - perl-extended-deps ==0.5.0


#test:
#  # Perl 'use' tests
#  imports:
#    - Ska::Convert

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

