package:
  name: perl-ska-web
  version: !!str 4.0

source:
 url: file:///proj/sot/ska/pkgs/Ska-Web-4.0.tar.gz

requirements:
  build:
    - perl
    - perl-core-deps
  run:
    - perl
    - perl-core-deps
test:
  # Perl 'use' tests
  imports:
    - Ska::Web

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

