package:
  name: perl-ska-web
  version: !!str 4.0

source:
 url: https://cxc.harvard.edu/mta/ASPECT/skare3-static-pkgs/Ska-Web-4.0.tar.gz

build:
  number: 2

requirements:
  host:
    - conda-forge::perl =5.32.1 # [linux]
    - perl # [osx]
    - perl-extended-deps
  run:
    - perl
    - perl-extended-deps
test:
  # Perl 'use' tests
  imports:
    - Ska::Web

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

